In [13]:
import pandas as pd

In [15]:
df=pd.read_csv('loan.csv')
df

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,Male,Engineer,Bachelor's,Married,85000,720,Approved
1,45,Female,Teacher,Master's,Single,62000,680,Approved
2,28,Male,Student,High School,Single,25000,590,Denied
3,51,Female,Manager,Bachelor's,Married,105000,780,Approved
4,36,Male,Accountant,Bachelor's,Married,75000,710,Approved
...,...,...,...,...,...,...,...,...
56,39,Male,Architect,Master's,Married,100000,770,Approved
57,25,Female,Receptionist,High School,Single,32000,570,Denied
58,43,Male,Banker,Bachelor's,Married,95000,760,Approved
59,30,Female,Writer,Master's,Single,55000,650,Approved
60,38,Male,Chef,Associate's,Married,65000,700,Approved

In [17]:
df.isna().sum()

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()
for column in ['gender','occupation','education_level','marital_status','income','loan_status']:
    df[column]=le.fit_transform(df[column])
df

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,1,12,1,0,24,720,0
1,45,0,35,4,1,15,680,0
2,28,1,33,3,1,0,590,1
3,51,0,16,1,0,31,780,0
4,36,1,0,1,0,20,710,0
...,...,...,...,...,...,...,...,...
56,39,1,2,4,0,30,770,0
57,25,0,27,3,1,3,570,1
58,43,1,4,1,0,28,760,0
59,30,0,37,4,1,12,650,0
60,38,1,5,0,0,16,700,0

In [23]:
x=df[['age','gender','occupation','education_level','marital_status','income','credit_score']]
x

,age,gender,occupation,education_level,marital_status,income,credit_score
0,32,1,12,1,0,24,720
1,45,0,35,4,1,15,680
2,28,1,33,3,1,0,590
3,51,0,16,1,0,31,780
4,36,1,0,1,0,20,710
...,...,...,...,...,...,...,...
56,39,1,2,4,0,30,770
57,25,0,27,3,1,3,570
58,43,1,4,1,0,28,760
59,30,0,37,4,1,12,650
60,38,1,5,0,0,16,700

In [25]:
y=df[['loan_status']]
y

    loan_status
0             0
1             0
2             1
3             0
4             0
..          ...
56            0
57            1
58            0
59            0
60            0

[61 rows x 1 columns]

In [27]:
ss=StandardScaler()
ss.fit_transform(x)

array([[-0.60822442,  0.98373875, -0.43329842, -0.75569778, -0.80538727,
         0.35125047,  0.14101548],
       [ 0.94765289, -1.01653005,  1.66296945,  1.43942435,  1.2416387 ,
        -0.48353961, -0.41394865],
       [-1.0869559 ,  0.98373875,  1.48068529,  0.70771697,  1.2416387 ,
        -1.87485641, -1.66261794],
       [ 1.66575011, -1.01653005, -0.06873009, -0.75569778, -0.80538727,
         1.00053165,  0.97346167],
       [-0.12949294,  0.98373875, -1.5270034 , -0.75569778, -0.80538727,
        -0.01976734,  0.00227444],
       [-1.56568738, -1.01653005,  0.20469615, -1.48740516,  1.2416387 ,
        -1.04006633, -0.96891278],
       [ 0.58860428,  0.98373875, -0.15987218, -0.02399041, -0.80538727,
         1.27879501,  1.1122027 ],
       [-0.96727303, -1.01653005, -1.25357715, -0.75569778,  1.2416387 ,
        -1.41108414, -1.24639485],
       [-0.00981007,  0.98373875, -0.25101426,  1.43942435, -0.80538727,
         0.62951383,  0.55723857],
       [ 1.3067015 , -1.01653005, -0.70672466, -0.02399041, -0.80538727,
         1.74256727,  1.5284258 ],
       [ 2.14448158,  0.98373875, -0.98015091,  1.43942435, -0.80538727,
         1.0932861 ,  0.83472064],
       [-0.72790729, -1.01653005, -1.43586132, -0.75569778,  1.2416387 ,
        -0.2980307 , -0.27520762],
       [-1.32632164,  0.98373875,  1.20725905,  0.70771697,  1.2416387 ,
        -1.22557524, -1.38513588],
       [ 0.22955567, -1.01653005,  0.02241199, -0.75569778, -0.80538727,
         0.07298711,  0.27975651],
       [ 0.82797002,  0.98373875, -1.34471923,  1.43942435, -0.80538727,
         0.72226829,  0.6959796 ],
       [-1.20663877, -1.01653005, -0.79786675, -0.75569778,  1.2416387 ,
        -0.85455742, -0.83017175],
       [-0.36885868,  0.98373875, -0.43329842, -0.75569778, -0.80538727,
         0.44400492,  0.41849754],
       [ 0.46892141, -1.01653005,  0.29583823, -0.02399041, -0.80538727,
         1.37154946,  1.25094373],
       [-0.84759016,  0.98373875,  1.02497488,  1.43942435,  1.2416387 ,
        -0.1125218 , -0.13646659],
       [ 1.90511584, -1.01653005,  0.56926448, -0.02399041, -0.80538727,
         0.81502274,  1.1122027 ],
       [ 0.1098728 ,  0.98373875,  0.47812239, -0.75569778, -0.80538727,
         0.16574156,  0.14101548],
       [-1.44600451, -1.01653005,  0.9338328 ,  0.70771697,  1.2416387 ,
        -1.5038386 , -1.80135898],
       [ 1.06733576,  0.98373875, -1.16243507,  1.43942435, -0.80538727,
         1.18604055,  0.97346167],
       [-0.48854155, -1.01653005,  1.84525362, -0.75569778,  1.2416387 ,
        -1.13282078, -1.10765381],
       [ 0.34923854,  0.98373875, -1.07129299, -1.48740516, -0.80538727,
        -0.57629406, -0.27520762],
       [-1.0869559 , -1.01653005,  1.75411154, -0.02399041,  1.2416387 ,
        -0.01976734,  0.00227444],
       [-0.24917581,  0.98373875,  1.11611696, -0.75569778, -0.80538727,
        -0.20527625, -0.13646659],
       [ 0.70828715, -1.01653005, -0.34215634,  1.43942435, -0.80538727,
         0.53675938,  0.55723857],
       [-0.72790729,  0.98373875, -0.5244405 ,  0.70771697,  1.2416387 ,
        -0.76180297, -0.55268969],
       [ 1.42638437, -1.01653005,  0.84269072, -0.75569778, -0.80538727,
        -0.39078516,  0.14101548],
       [-1.20663877,  0.98373875,  0.38698031, -1.48740516,  1.2416387 ,
        -1.31832969, -1.52387691],
       [ 2.02479871, -1.01653005, -0.61558258,  1.43942435, -0.80538727,
         0.35125047,  0.6959796 ],
       [-0.60822442,  0.98373875,  0.66040656, -0.75569778, -0.80538727,
         0.72226829,  0.97346167],
       [ 1.18701863, -1.01653005, -0.88900883, -0.02399041, -0.80538727,
         1.55705837,  1.38968477],
       [-0.96727303,  0.98373875,  0.11355407, -0.75569778,  1.2416387 ,
        -1.68934751, -1.94010001],
       [ 1.78543298, -1.01653005,  0.75154864, -0.02399041, -0.80538727,
         1.0932861 ,  1.25094373],
       [-0.24917581,  0.98373875, -0.43329842,  1.43942435, -0.80538727,
         0.90777719,  0.83472064],
       [-1.32632164, -1.01653005,  1.29840113,  0.70771697,  1.2416387 ,
        -1.78210196, -2.07884104],
       [ 0.34923854,  0.98373875,  1.38954321, -0.75569778, -0.80538727,
         0.35125047,  0.41849754],
       [-0.48854155, -1.01653005,  1.57182737, -1.48740516,  1.2416387 ,
        -1.22557524, -1.24639485],
       [ 0.1098728 ,  0.98373875, -1.5270034 , -0.75569778, -0.80538727,
         0.25849602,  0.27975651],
       [-0.84759016, -1.01653005,  1.66296945,  1.43942435,  1.2416387 ,
        -0.66904852, -0.55268969],
       [ 0.94765289,  0.98373875, -0.06873009, -0.75569778, -0.80538727,
         1.0932861 ,  1.1122027 ],
       [-1.0869559 , -1.01653005,  0.20469615, -1.48740516,  1.2416387 ,
        -0.94731188, -0.69143072],
       [ 0.58860428,  0.98373875, -0.15987218, -0.02399041, -0.80538727,
         1.46430391,  1.25094373],
       [-0.12949294, -1.01653005, -0.43329842,  1.43942435, -0.80538727,
         0.53675938,  0.41849754],
       [-0.72790729,  0.98373875, -1.43586132, -0.75569778,  1.2416387 ,
        -0.39078516, -0.41394865],
       [ 1.3067015 , -1.01653005, -0.70672466, -0.02399041, -0.80538727,
         1.64981282,  1.66716683],
       [-0.36885868,  0.98373875, -0.25101426, -0.75569778, -0.80538727,
         0.07298711,  0.14101548],
       [-1.20663877, -1.01653005, -1.25357715, -0.75569778,  1.2416387 ,
        -1.5038386 , -1.52387691],
       [ 0.46892141,  0.98373875, -0.98015091,  1.43942435, -0.80538727,
         1.00053165,  0.6959796 ],
       [-0.96727303, -1.01653005, -0.79786675, -0.75569778,  1.2416387 ,
        -1.04006633, -0.96891278],
       [-0.00981007,  0.98373875, -0.43329842, -0.75569778, -0.80538727,
         0.62951383,  0.55723857],
       [ 0.82797002, -1.01653005,  0.02241199,  1.43942435, -0.80538727,
         0.35125047,  0.41849754],
       [-0.60822442,  0.98373875,  1.20725905,  0.70771697,  1.2416387 ,
        -1.13282078, -1.10765381],
       [ 1.54606724, -1.01653005,  0.56926448, -0.02399041, -0.80538727,
         1.27879501,  1.38968477],
       [ 0.22955567,  0.98373875, -1.34471923,  1.43942435, -0.80538727,
         0.90777719,  0.83472064],
       [-1.44600451, -1.01653005,  0.9338328 ,  0.70771697,  1.2416387 ,
        -1.59659305, -1.94010001],
       [ 0.70828715,  0.98373875, -1.16243507, -0.75569778, -0.80538727,
         0.72226829,  0.6959796 ],
       [-0.84759016, -1.01653005,  1.84525362,  1.43942435,  1.2416387 ,
        -0.76180297, -0.83017175],
       [ 0.1098728 ,  0.98373875, -1.07129299, -1.48740516, -0.80538727,
        -0.39078516, -0.13646659]])

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
print(x_train,x_test,y_train,y_test)

    age  gender  occupation  education_level  marital_status  income  \
4    36       1           0                1               0      20
44   42       1          15                2               0      36
19   53       0          23                2               0      29
47   48       0           9                2               0      38
52   37       1          12                1               0      27
25   28       0          36                2               1      20
57   25       0          27                3               1       3
15   27       0           8                1               1      11
58   43       1           4                1               0      28
27   43       0          13                4               0      26
9    48       0           9                2               0      39
30   27       1          21                0               1       6
36   35       1          12                4               0      30
26   35       1          29                1               0      18
24   40       1           5                0               0      14
43   28       0          19                0               1      10
11   31       0           1                1               1      17
32   32       1          24                1               0      28
54   32       1          30                3               1       8
56   39       1           2                4               0      30
37   26       0          31                3               1       1
29   49       0          26                1               0      16
45   36       0          12                4               0      26
1    45       0          35                4               1      15
21   25       0          27                3               1       4
2    28       1          33                3               1       0
48   34       1          14                1               0      21
39   33       0          34                0               1       7
35   52       0          25                2               0      32
23   33       0          37                1               1       8
50   41       1           6                4               0      31
10   55       1           6                4               0      32
22   46       1           4                4               0      33
18   30       1          28                4               1      19
60   38       1           5                0               0      16
20   38       1          22                1               0      22
7    29       0           3                1               1       5
42   45       1          16                1               0      32
14   44       1           2                4               0      28
28   31       1          11                3               1      12
51   29       0           8                1               1       9
38   40       1          32                1               0      24

    credit_score
4            710
44           800
19           790
47           830
52           750
25           710
57           570
15           650
58           760
27           750
9            820
30           600
36           770
26           700
24           690
43           660
11           690
32           780
54           630
56           770
37           560
29           720
45           740
1            680
21           580
2            590
48           720
39           620
35           800
23           630
50           760
10           770
22           780
18           700
60           700
20           720
7            620
42           790
14           760
28           670
51           640
38           740       age  gender  occupation  education_level  marital_status  income  \
0    32       1          12                1               0      24
5    24       0          19                0               1       9
46   31       1           1                1               1      16
31   54       0          10                4               0      24
13   39       0          17                1               0      21
55   50       0          23                2               0      34
34   29       1          18                1               1       2
49   27       0           3                1               1       4
12   26       1          30                3               1       7
40   38       1           0                1               0      23
33   47       0           7                2               0      37
59   30       0          37                4               1      12
16   34       1          12                1               0      25
3    51       0          16                1               0      31
53   44       0          17                4               0      24
17   41       0          20                2               0      35
8    37       1          14                4               0      27
6    42       1          15                2               0      34
41   30       0          35                4               1      13

    credit_score
0            720
5            640
46           680
31           760
13           730
55           810
34           570
49           600
12           610
40           730
33           810
59           650
16           740
3            780
53           740
17           800
8            750
6            790
41           670       loan_status
4             0
44            0
19            0
47            0
52            0
25            0
57            1
15            1
58            0
27            0
9             0
30            1
36            0
26            0
24            0
43            1
11            0
32            0
54            1
56            0
37            1
29            0
45            0
1             0
21            1
2             1
48            0
39            1
35            0
23            1
50            0
10            0
22            0
18            0
60            0
20            0
7             1
42            0
14            0
28            0
51            1
38            0     loan_status
0             0
5             1
46            0
31            0
13            0
55            0
34            1
49            1
12            1
40            0
33            0
59            0
16            0
3             0
53            0
17            0
8             0
6             0
41            0

In [31]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
model

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [33]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [35]:
acc=accuracy_score(y_test,y_pred)
acc

0.9473684210526315

In [37]:
cc=confusion_matrix(y_test,y_pred)
cc

array([[14,  1],
       [ 0,  4]], dtype=int64)

In [39]:
ccc=classification_report(y_test,y_pred)
ccc

'              precision    recall  f1-score   support\n\n           0       1.00      0.93      0.97        15\n           1       0.80      1.00      0.89         4\n\n    accuracy                           0.95        19\n   macro avg       0.90      0.97      0.93        19\nweighted avg       0.96      0.95      0.95        19\n'

In [41]:
pp=precision_score(y_test,y_pred)
pp

0.8

In [43]:
new_data=np.array([[32,1,12,1,0,24,720]])
new=ss.transform(new_data)
predicted_prob=model.predict(new)
print(predicted_prob[0])

1

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(